### ISSUE TITLE
Ubuntu 16: Python 3.5 SSL certificate errors

### ISSUE THREAD

**Issue by mgrady3** [DonaldKBrown/BitMon#1]
Before mentioning the mian problem I'll point out that you should add to your 'requirements' section that users may need to ensure that the 'dialog' executable is installed, on linux (ubuntu) this can just be 'sudo apt install dialog'. Pythondialog isn't enough if the dialog executable isn't present.

Now to the main point.

Using Ubuntu 16,  Python 3.5 via Anaconda with Requests=2.11.1 and pythondialog=3.4.0

Upon executing python bitmon-client.py I get a lot of errors about SSL certificates

requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

**Comment by DonaldKBrown** [comment]
That's strange, the certificate is issued from let's encrypt and the server runs as flask behind an Apache proxy. I, personally, haven't seen any issues. I'll check into this.

**Comment by DonaldKBrown** [comment]
This latest commit fixed the issue of not referencing the need for `dialog` to be installed. Also, I've reissued the Let's Encrypt certificate and restarted the Apache server. Could you see if you're still getting SSL errors? I'm not seeing any on my test machines, running Ubuntu ranging from 14.04 to 16.04.

**Comment by mgrady3** [comment]
I reinstalled bitmon-clieny.py, and restarted my virtual machine.

Now all is working.

Thanks!
